### PR TITLE
Include builderLabels in duplicate asset exception

### LINKED ISSUE #1273: Report builder keys when there is a conflicting output

### PR DESCRIPTION
**Pull request by natebosch**
Closes #1273
Start towards #1431

- Pass through the `BuildPhase`s and `rootPackage` so that the builder
  labels and a friendlier string for the AssetId can be used.
- Catch and log the duplicate asset exception when it occurs while
  loading the build definition. Throw a `CannotBuildException` to cancel
  the overall build without printing a stack trace.
- Add an FAQ section for this problem.
- Catch all exceptions from updating the asset graph when they occur
  during the build.

### CODE REVIEW

**Comment by natebosch** [comment]
New output looks like:

```
[INFO] Generating build script completed, took 421ms
[SEVERE] Both pageloader and built_value_generator|built_value may output lib/hero.g.dart. Potential outputs must be unique across all builders. See https://github.com/dart-lang/build/blob/master/docs/faq.md#why-do-builders-need-unique-outputs
```

File: build_runner/lib/src/generate/build_definition.dart [hunk 1]
```diff
@@ -101,8 +101,13 @@ class _Loader {
       Set<AssetId> conflictingOutputs;
 
       await logTimedAsync(_logger, 'Building new asset graph', () async {
-        assetGraph = await AssetGraph.build(_buildPhases, inputSources,
-            internalSources, _options.packageGraph, _environment.reader);
+        try {
+          assetGraph = await AssetGraph.build(_buildPhases, inputSources,
+              internalSources, _options.packageGraph, _environment.reader);
+        } on DuplicateAssetNodeException catch (e) {
+          _logger.severe('$e');
```
Comment (jakemac53) [inline build_runner/lib/src/generate/build_definition.dart]: lets attach the stack trace as well, so we get it in verbose mode.

File: docs/faq.md [hunk 2]
```diff
@@ -0,0 +1,15 @@
+## Why do Builders need unique outputs?
+
+`build_runner` relies on determining a static build graph before starting a
+build - it needs to know every file that may be written and which Builder would
```
Comment (grouma) [inline docs/faq.md]: [nit] Why capitalize Builder here but not below?

Comment (natebosch) [reply docs/faq.md]: No idea. going with all capitals for now.

File: build_runner/lib/src/generate/build_definition.dart (hunk 1 above)
Comment (natebosch) [reply build_runner/lib/src/generate/build_definition.dart]: Done
