### PR TITLE
Fix resolver behavior when encountering non-existing asset ids

### LINKED ISSUE #2389: Generated Dart code is not visible to other builders if library is resolved twice
## Problem
We have two builders (one custom defined below, one from `built_value`) generating different Dart files that should be `part of` a user defined library:
```dart
// this is the input, called example.dart
import 'package:built_value/built_value.dart';

part 'example.sample.dart'; // generated by a custom builder, source below
part 'example.g.dart'; // generated by built_value with source_gen

abstract class Example implements Built<Example, ExampleBuilder> {
  SomeClass get entry; // defined in "example.sample.dart"

  Example._();
  factory Example([void Function(ExampleBuilder) updates]) = _$Example;
}
```

The custom builder looks like this, it basically writes `SomeClass` into a part file for the `example.dart` file above:
```dart
import 'dart:async';
import 'package:build/build.dart';
Builder createSomeBuilder([BuilderOptions options]) => SimpleBuilder();

class SimpleBuilder extends Builder {
  @override
  FutureOr<void> build(BuildStep buildStep) async {
    final input = buildStep.inputId;
    log.fine('Running build-use-generated-dart on ${input.path}');
    if (input.path.endsWith('example.dart')) {
      final output = input.changeExtension('.sample.dart');

      // the issue only occurs when the next line is present!!
      await buildStep.inputLibrary;

      await buildStep.writeAsString(output, r'''
part of 'example.dart';
class SomeClass {
  final String field;
  const SomeClass(this.field);
}''');
    }
  }
  @override
  final Map<String, List<String>> buildExtensions = const {
    'dart': ['sample.dart']
  };
}
```

When the `await buildStep.inputLibrary` is commented out, the build runs without a problem and the generated code from `built_value` contains the `SomeClass` field.   
However, when `await buildStep.inputLibrary` is uncommented, it looks like `built_value` is unable to resolve the generated class:
```
[SEVERE] built_value_generator:built_value on lib/example.dart:
Error in BuiltValueGenerator for abstract class Example implements Built<Example, dynamic>.
Please make the following changes to use BuiltValue:

1. Make field entry have non-dynamic type. If you are already specifying a type, please make sure the type is correctly imported.
package:built_value_generator/src/value_source_class.dart 575:28        ValueSourceClass.generateCode
package:built_value_generator/built_value_generator.dart 53:52          BuiltValueGenerator.generate
package:source_gen/src/builder.dart 280:35                              _generate
package:source_gen/src/builder.dart 73:15                               _Builder._generateForLibrary
package:source_gen/src/builder.dart 67:11                               _Builder.build
package:build                                                           runBuilder
```

We have a `build.yaml` configured so that the `built_value_generator` will always run second.

I've uploaded the full example here: https://drive.google.com/file/d/1KQ-XA0I-ouHKzxGChHIDXZg24pto37Lu/view?usp=sharing

## Potential cause
I don't know really how the `Resolver` works, but this seems like it's caching the analyzer result for `inputLibrary`. When the analyzer is invoked at a point in which `example.sample.dart` has already been generated, there is no problem.
However, if the first builder already uses `await buildStep.inputLibrary`, the analysis result at that point (which obviously doesn't include `SomeClass`) will also be used on `built_value`, causing the problem.

If there is a cache, maybe a file should be invalidated whenever a `part` or `import` changes?

## Versions
My Dart SDK version is `Dart VM version: 2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "linux_x64"`. I use the following version of packages which could be relevant here:
* `analyzer: 0.36.4`
* `build: 1.1.5`
* `build_resolvers: 1.0.6`
* `build_runner: 1.6.5`
* `build_runner_core: 3.0.7`
* `built_value_generator: 6.7.0`

### PR DESCRIPTION
**Pull request by simolus3**
I follow the advice from https://github.com/dart-lang/build/issues/2389#issuecomment-582595934. Basically, we're not supposed to return a null source if the uri could refer to a valid asset id. However, we used to return null if we haven't seen the asset id yet (e.g. it doesn't exist). Now, we just return the source pointing to the file where a non-existing asset id would be. If it gets created in a later build step, the analyzer will recognize this and handle it correctly.

With manual testing, I can verify that this indeed fixes #2389. Also contains, and thus closes #2392.

### CODE REVIEW

**Comment by jakemac53** [comment]
woooo! :tada:

File: build_resolvers/lib/src/build_asset_uri_resolver.dart [hunk 1]
```diff
@@ -130,16 +143,18 @@ class BuildAssetUriResolver extends UriResolver {
 
   @override
   Source resolveAbsolute(Uri uri, [Uri actualUri]) {
-    final cachedId = lookupAsset(uri);
-    if (cachedId == null) return null;
-    return resourceProvider
-        .getFile(assetPath(cachedId))
-        .createSource(cachedId.uri);
+    final assetId = parseAsset(uri);
+    if (assetId == null) {
```
Comment (jakemac53) [inline build_resolvers/lib/src/build_asset_uri_resolver.dart]: nit: for this one I would just do a one liner `if (assetId == null) return null;`

File: build_resolvers/lib/src/build_asset_uri_resolver.dart [hunk 2]
```diff
@@ -130,16 +143,18 @@ class BuildAssetUriResolver extends UriResolver {
...
+      return null;
+    }
+    final source =
```
Comment (jakemac53) [inline build_resolvers/lib/src/build_asset_uri_resolver.dart]: nit: just return right away we don't need the local variable

File: build_resolvers/pubspec.yaml [hunk 3]
```diff
@@ -1,5 +1,5 @@
 name: build_resolvers
-version: 1.3.2
+version: 1.3.3-dev
```
Comment (jakemac53) [inline build_resolvers/pubspec.yaml]: Go ahead and remove the `-dev` - I can publish this after the merge

File: build_resolvers/lib/src/build_asset_uri_resolver.dart [hunk 4]
```diff
@@ -130,16 +143,18 @@ class BuildAssetUriResolver extends UriResolver {
...
+        resourceProvider.getFile(assetPath(assetId)).createSource(assetId.uri);
+    return source;
   }
 
   @override
   Uri restoreAbsolute(Source source) =>
-      lookupAsset(source.uri)?.uri ?? source.uri;
+      lookupCachedAsset(source.uri)?.uri ?? source.uri;
```
Comment (simolus3) [inline build_resolvers/lib/src/build_asset_uri_resolver.dart]: I'm not sure if we should enforce the asset being cached here, or if we can just remove `lookupCachedAsset` entirely. The documentation from `UriResolver` says that `restoreAbsolute` "should be based solely on [source.fullName].", to me that sounds like further checks unnecessary. What do you think, @jakemac53?

Comment (jakemac53) [reply build_resolvers/lib/src/build_asset_uri_resolver.dart]: Tbh I would just go for the minimal change (what we have here). This code has always been very fragile and I am not sure what it might break.

@scheglov would know the most though.

Comment (jakemac53) [reply build_resolvers/lib/src/build_asset_uri_resolver.dart]: I am going to go ahead and merge/publish as this isn't changing the behavior. If we decide to change it further we can always do a followup :).

**Comment by jakemac53** [comment]
published!
